core/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('plays/', AllPlays.as_view(), name='all-plays'),
    path('plays/<slug:slug>/', PlayDetailsView.as_view(), name='play-details'),
    path('create_play/', CreatePlay.as_view(), name='create-play'),
    path('<slug:slug>/edit/', EditPlay.as_view(), name='edit-play'),
    path('<slug:slug>/delete/', DeletePlay.as_view(), name='delete-play'),
    path('search/', search_plays, name='search_results'),
    path('profile/', profile, name='profile'),

    path('news/', AllNews.as_view(), name='all-news'),
    path('create_news/', NewsCreate.as_view(), name='create-news'),
    path('news_details/<int:pk>', NewsDetails.as_view(), name='details-news'),
    path('news_edit/<int:pk>', NewsEdit.as_view(), name='edit-news'),
    path('news_delete/<int:pk>', NewsDelete.as_view(), name='delete-news'),


    path('artists/', AllArtists.as_view(), name='all-artists'),
    path('create_artist/', ArtistCreate.as_view(), name='create-artist'),
    path('artists_details/<int:pk>', ArtistDetails.as_view(), name='details-artist'),
    path('artists_edit/<int:pk>/', ArtistEdit.as_view(), name='edit-artist'),
    path('artists_delete/<int:pk>', ArtistDelete.as_view(), name='delete-artist'),

]

django_website/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import handler404, handler403, handler400, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),

    # reference the authentication system
    path('membership/', include('django.contrib.auth.urls')),

    path('membership/', include('membership.urls')),
]

handler400 = handler400
handler404 = handler404
handler403 = handler403
handler500 = handler500

core/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from datetime import datetime


class Artist(models.Model):
    first_name = models.CharField('First Name', max_length=15, blank=False, null=False)
    last_name = models.CharField('Last Name', max_length=15, blank=False, null=False)
    birth_date = models.CharField('Birth Date', max_length=10, blank=True, null=True)
    photo = models.ImageField('Photo', blank=True, null=True)
    bio = models.CharField('Bio', max_length=400, blank=False, null=False)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Play(models.Model):
    title = models.CharField('Title', max_length=30, unique=True, blank=False, null=False)
    genre = models.CharField('Genre', max_length=15, blank=False, null=False)
    date = models.DateField('Date', blank=False, null=False)
    time = models.TimeField('Time', blank=False, null=False)
    description = models.CharField('Description', max_length=360, blank=True, null=True)
    artists = models.ForeignKey(Artist, on_delete=models.CASCADE, blank=True, null=True)
    slug = models.SlugField(unique=True)
    price = models.CharField('Price', max_length=10, blank=False, null=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Play, self).save(*args, **kwargs)

    class Meta:
        ordering = ['date']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('play-details', kwargs={"slug": self.slug})


class Ticket(models.Model):
    seat_number = models.IntegerField('Seat Number', unique=True)
    price = models.DecimalField('Price', max_digits=5, decimal_places=2)
    play = models.ForeignKey(Play, on_delete=models.CASCADE)

    def __str__(self):
        return f"Play {self.play} - Seat: {self.seat_number} - Date: {self.play.date} - Time: {self.play.time}"


class User(models.Model):
    username = models.CharField('username', max_length=30, blank=False, null=False)
    password = models.CharField('password', max_length=30, blank=False, null=False)
    email = models.EmailField('E-mail', blank=False, null=False)
    first_name = models.CharField('First Name', max_length=60, blank=False, null=False)
    last_name = models.CharField('Last Name', max_length=60, blank=False, null=False)
    tickets = models.ManyToManyField(Ticket)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class News(models.Model):
    title = models.CharField('Title', max_length=30, unique=True, blank=False, null=False)
    date = models.DateField('Date', blank=False, null=False, default=datetime.now)
    time = models.TimeField('Time', blank=False, null=False, default=datetime.now)
    content = models.CharField('Content', max_length=360, blank=True, null=True)

    class Meta:
        ordering = ['date']

core/forms.py
from django import forms
from django.forms import ModelForm
from .models import *


class PlayForm(ModelForm):
    class Meta:
        model = Play
        fields = ('title', 'genre', 'time', 'date', 'description', 'artists', 'price')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'input', 'type': 'text', 'placeholder': 'Title'}),
            'genre': forms.TextInput(attrs={'class': 'input', 'type': 'text', 'placeholder': 'Genre'}),
            'time': forms.TimeInput(attrs={'class': 'input', 'type': 'time', 'placeholder': 'Time'}),
            'date': forms.DateInput(attrs={'class': 'input', 'type': 'date', 'placeholder': 'Date'}),
            'description': forms.Textarea(attrs={'class': 'textarea', 'type': 'text', 'placeholder': 'Description', 'rows': '10'}),
            'artists': forms.Select(attrs={'class': 'input', 'type': 'select', 'placeholder': 'Description', 'rows': '10'}),
            'price': forms.TextInput(attrs={'class': 'input', 'type': 'text', 'placeholder': 'Price'}),
        }


class ArtistForm(ModelForm):
    class Meta:
        model = Artist
        fields = ('first_name', 'last_name', 'bio')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'input', 'type': 'text', 'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'class': 'input', 'type': 'text', 'placeholder': 'Last Name'}),
            'bio': forms.Textarea(attrs={'class': 'textarea', 'type': 'text', 'placeholder': 'Bio'}),
        }


class NewsForm(ModelForm):
    class Meta:
        model = News
        fields = ('title', 'time', 'date', 'content')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'input', 'type': 'text', 'placeholder': 'Title'}),
            'time': forms.TimeInput(attrs={'class': 'input', 'type': 'time', 'placeholder': 'Time'}),
            'date': forms.DateInput(attrs={'class': 'input', 'type': 'date', 'placeholder': 'Date'}),
            'content': forms.Textarea(attrs={'class': 'textarea', 'type': 'text', 'placeholder': 'Content', 'rows': '10'}),
        }

core/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from . models import *
from django.views import generic as views
from .forms import PlayForm, NewsForm, ArtistForm
from django.template import loader
from django.http import HttpResponse, response


def handler404(request, *args, **kwargs):
    template = loader.get_template('errors/404_not_found.html')
    response.status_code = 404
    return HttpResponse(template.render({}, request), status=404)


def handler403(request, *args, **kwargs):
    template = loader.get_template('errors/403.html')
    response.status_code = 403
    return HttpResponse(template.render({}, request), status=403)


def handler400(request, *args, **kwargs):
    template = loader.get_template('errors/400_bad_request.html')
    response.status_code = 400
    return HttpResponse(template.render({}, request), status=400)


def handler500(request, *args, **kwargs):
    template = loader.get_template('errors/500_error.html')
    response.status_code = 500
    return HttpResponse(template.render({}, request), status=500)


class Home(views.TemplateView):
    template_name = 'core/home.html'
    date = datetime.now()
    plays = Play.objects.all()
    latest_news = News.objects.filter()[:1].get()
    artists = Artist.objects.all()
    extra_context = {'date': date, 'plays': plays, 'latest_news': latest_news, 'artists': artists}


class AllPlays(views.ListView):
    model = Play
    context_object_name = 'plays'
    template_name = 'core/all_plays.html'


class PlayDetailsView(views.DetailView):
    model = Play
    template_name = 'core/play_details.html'
    context_object_name = 'play'


class CreatePlay(views.CreateView):
    template_name = 'core/play_create.html'
    form_class = PlayForm
    success_url = reverse_lazy('all-plays')


class EditPlay(views.UpdateView):
    model = Play
    form_class = PlayForm
    template_name = 'core/play_edit.html'
    context_object_name = 'play'
    success_url = reverse_lazy('all-plays')


class DeletePlay(views.DeleteView):
    model = Play
    template_name = 'core/delete-confirm.html'
    success_url = reverse_lazy('all-plays')


def search_plays(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        plays = Play.objects.filter(title__contains=searched)
        artists = Artist.objects.filter(Q(first_name__contains=searched) | Q(last_name__contains=searched))
        news = News.objects.filter(title__contains=searched)
        number_of_items = len(plays) + len(artists) + len(news)
        context = {'plays': plays, 'news': news, 'artists': artists, 'searched': searched, 'number_of_plays': number_of_items}
        return render(request, 'core/search.html', context)


def profile(request):
    return render(request, 'core/profile.html', {})


class AllNews(views.ListView):
    model = News
    template_name = 'core/news_all.html'
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super(AllNews, self).get_context_data(**kwargs)
        news = News.objects.all()
        paginator = Paginator(news, self.paginate_by)

        page = self.request.GET.get('page')

        try:
            file_news = paginator.page(page)
        except PageNotAnInteger:
            file_news = paginator.page(1)
        except EmptyPage:
            file_news = paginator.page(paginator.num_pages)

        context['all_news'] = file_news
        return context


class NewsCreate(views.CreateView):
    template_name = 'core/news_create.html'
    form_class = NewsForm
    success_url = reverse_lazy('all-news')


class NewsDetails(views.DetailView):
    template_name = 'core/news_details.html'
    model = News
    context_object_name = 'news'


class NewsEdit(views.UpdateView):
    model = News
    form_class = NewsForm
    template_name = 'core/news_edit.html'
    context_object_name = 'news'
    success_url = reverse_lazy('all-news')


class NewsDelete(views.DeleteView):
    model = News
    template_name = 'core/delete-confirm.html'
    success_url = reverse_lazy('all-news')


class AllArtists(views.ListView):
    model = Artist
    context_object_name = 'artists'
    template_name = 'core/artists_all.html'


class ArtistCreate(views.CreateView):
    template_name = 'core/artists_create.html'
    form_class = ArtistForm
    success_url = reverse_lazy('all-artists')


class ArtistDetails(views.DetailView):
    model = Artist
    template_name = 'core/artists_details.html'
    context_object_name = 'artists'


class ArtistEdit(views.UpdateView):
    model = Artist
    form_class = ArtistForm
    template_name = 'core/artists_edit.html'
    context_object_name = 'artists'
    success_url = reverse_lazy('all-artists')


class ArtistDelete(views.DeleteView):
    model = Artist
    template_name = 'core/delete-confirm.html'
    success_url = reverse_lazy('all-artists')

templates/core/Base.html
<!DOCTYPE html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Welcome to My local theatre!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  </head>

    {% include 'core/navbar.html' %}

<body>
 <div class="hero-body is-one-fifth is-align-self-center">
 <div class="columns">
     <div class="column is-one-fifth"></div>
     <div class="column">
                 {% if messages %}
            {% for message in messages %}
                <article class="message">
                  <div class="message-header"><p>Message</p></div>
                <div class="message-body">{{ message }}</div>
                </article>
            {% endfor %}
        {% endif %}
     </div>
     <div class="column is-one-fifth"></div>
 </div>

        {% block content %}

        {% endblock %}
 </div>

</body>

<br><br><br><br><br><br><br><br><br><br>
        <footer class="footer is-fixed-bottom">
              <div class="has-text-centered">
                  <p>This is a school project by Hristo Kutsarov for <a href="https://softuni.bg/">@SoftUni</a></p>
              </div>
        </footer>


</html>

templates/core/all_events.html
{% extends 'core/Base.html' %}
{% load static %}

{% block content %}

<div class="class-section">
    <div class="table-container">
        <div class="columns mt-3 is-1 is-variable">

            {% for event in object_list %}

            <div class="column is-4-tablet is-3-desktop">
                <div class="card help">
                    <div class="card-image has-text-centered px-6">
                        <img src="{% static 'sample_picture.jpg' %}" alt="">
                    </div>
                    <div class="card-content">
                        <p>{{ event.date }} {{ event.time }}</p>
                        <p class="title is-size-5">{{ event.title }}</p>
                    </div>
                    <footer class="card-footer">
                        <p class="card-footer-item"><span><a href="#">View</a></span></p>
                        <p class="card-footer-item"><span><a href="#">Edit</a></span></p>
                        <p class="card-footer-item"><span><a href="#">Delete</a></span></p>
                    </footer>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <br>

</div>

{% endblock %}

templates/core/all_plays.html
{% extends 'core/Base.html' %}
{% load static %}

{% block content %}

<div class="container is-fullheight">
    <div class="table-container is-fullheight">
        <div class="columns mt-3 is-1 is-variable">

        {% if plays %}
            {% for play in plays %}
            <div class="column is-4-tablet is-3-desktop">
                <div class="card help">
                    <div class="card-image has-text-centered px-6">
                        <a href="{% url 'play-details' slug=play.slug %}"><img src="{% static 'sample_picture.jpg' %}" alt=""></a>
                    </div>
                    <div class="card-content">
                        <p>{{ play.date }} {{ play.time }}</p>
                        <br>
                        <p class="title is-size-5">{{ play.title }}</p>
                        <br>
                        <p class="title is-size-6"><span>{{ play.price }}</span></p>
                    </div>
                    <footer class="card-footer">
                        {% if perms.core.change_play %}
                        <p class="card-footer-item"><span><a href="{% url 'edit-play' slug=play.slug %}">Edit</a></span></p>
                        {% endif %}
                        {% if perms.core.delete_play %}
                        <p class="card-footer-item"><span><a href="{% url 'delete-play' slug=play.slug %}">Delete</a></span></p>
                        {% endif %}
                    </footer>
                </div>
            </div>

            {% endfor %}

            {% else %}

                <article class="message">
                  <div class="message-header"><p>Message</p></div>
                <div class="message-body">This page has no content.</div>
                </article>

        {% endif %}
        </div>
    </div>
</div>
<div class="columns">
<div class="column is-one-fifth"></div>

    <div class="column">
        <div class="container default">
        <div class="section heading is-centered">
            <h5 class="title has-text-grey-light  has-text-centered is-bold">Details</h5>
        </div>
    </div>

  <div class="table-container is-max-desktop">
  <table class="table is-vcentered">

    <!-- Your table content -->
  <thead>
    <tr>
      <th><abbr title="Position">No.</abbr></th>
      <th><abbr title="Played">Title</abbr></th>
      <th><abbr title="Won">Date</abbr></th>
      <th><abbr title="Drawn">Time</abbr></th>
      <th><abbr title="Lost">Artists</abbr></th>
      <th><abbr title="Goals for">Price</abbr></th>
      <th><abbr title="Goals for">Price</abbr></th>
      <th><abbr title="Goals for">Price</abbr></th>
      <th><abbr title="Goals for">Price</abbr></th>
    </tr>
  </thead>

  <tbody>
  {% for play in plays %}
    <tr>
      <th>{{ play.pk }}</th>
        <td><a href="{% url 'play-details' slug=play.slug %}">{{ play.title }}</a></td>
      <td>{{ play.date }}</td>
      <td>{{ play.time }}</td>
      <td>{{ play.artists }}</td>
      <td>{{ play.price }}</td>
      <td>{{ play.price }}</td>
      <td>{{ play.price }}</td>
      <td>{{ play.price }}</td>
    </tr>
 {% endfor %}

  </tbody>

  </table>
</div>
    </div>
<div class="column is-one-fifth"></div>
</div>


{% endblock %}

templates/core/artists_create.html
{% extends 'core/Base.html' %}

{% load static %}
{% block content %}

<div class="container is-fullheight">
    <div class="columns">
        <div class="column is is-one-fifth"></div>
        <div class="column">
            {% if perms.core.add_artist %}
            <h1><strong>Create artist</strong></h1>
        <br>
                <form method="post">

                {% csrf_token %}

                {{ form.as_p }}

                <br>

                <div class="mb-3"><button class="button is-medium">Submit</button></div>

                </form>

                {% else %}
                <article class="message">
                  <div class="message-header"><p>Message</p></div>
                <div class="message-body">You have no permissions to view this page.</div>
                </article>
            {% endif %}
            </div>
        <div class="column is is-one-fifth"></div>
        </div>
    </div>
</div>



{% endblock %}

templates/core/artists_details.html
{% extends 'core/Base.html' %}

{% load static %}
{% block content %}

<div class="container is-fullheight">
    <div class="columns">
        <div class="column is is-one-fifth"></div>
        <div class="column">

        <div class="box">

  <article class="media">
    <div class="media-left">
      <figure class="image is-align-self-auto">
        <a href="#"><img src="{% static 'sample_logo.png' %}" alt="Image"></a>
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <p>
          <strong>{{ artists.first_name }} {{ artists.last_name }}</strong>
          <br>
          {{ artists.bio }}
        </p>
      </div>
      <nav class="level">
        <div class="level-right">
        {% if perms.core.change_artist %}
            <button class="button is-small"><a href="{% url 'edit-artist' pk=artists.pk %}">Edit</a></button>
        {% endif %}
        {% if perms.core.delete_artist %}
            <button class="button is-small"><a href="{% url 'delete-artist' pk=artists.pk %}">Delete</a></button>
        {% endif %}
        </div>
      </nav>

    </div>
  </article>
</div>
            
        </div>
        <div class="column is is-one-fifth"></div>
        </div>
    </div>

{% endblock %}

templates/core/delete-confirm.html
{% extends 'core/Base.html' %}

{% load static %}

{% block content %}

        <div class="columns is-fullheight">
        <div class="column is-one-fifth"></div>
        <div class="column ">
            <div class="container">
                {% if perms.core.delete_play or perms.core.delete_news or perms.core.delete_artist %}
             <form method="post">{% csrf_token %}

                <p class="title is-center">Are you sure you want to delete "{{ object }}"?</p>

                 <button class="button is-medium">Yes</button>

             </form>
                {% else %}

                <article class="message">
                  <div class="message-header"><p>Message</p></div>
                <div class="message-body">You have no permissions to view this page.</div>
                </article>

                {% endif %}
            </div>
        </div>
        <div class="column is-one-fifth"></div>
        </div>
    </div>
{% endblock %}

templates/core/home.html
{% extends 'core/Base.html' %}
{% load static %}


{% block content %}
{% if plays %}
<div class="container default ce">
    <div class="section heading is-centered">
        <h4 class="title has-text-grey-light  has-text-centered is-bold">My local theatre tickets</h4>
    </div>
</div>
<div class="container is-fullheight">
    <div class="table-container is-fullheight">
        <div class="columns mt-3 is-1 is-variable">

            {% for play in plays %}
            <div class="column is-4-tablet is-3-desktop">
                <div class="card help">
                    <div class="card-image has-text-centered px-6">
                        <a href="{% url 'play-details' slug=play.slug %}"><img src="{% static 'sample_picture.jpg' %}" alt=""></a>
                    </div>
                    <div class="card-content">
                        <p>{{ play.date }} {{ play.time }}</p>
                        <br>
                        <p class="title is-size-5">{{ play.title }}</p>
                        <br>
                        <p class="title is-size-6"><span>{{ play.price }}</span></p>
                    </div>
                    <footer class="card-footer">
                        {% if perms.core.change_play %}
                        <p class="card-footer-item"><span><a href="{% url 'edit-play' slug=play.slug %}">Edit</a></span></p>
                        {% endif %}
                        {% if perms.core.delete_play %}
                        <p class="card-footer-item"><span><a href="{% url 'delete-play' slug=play.slug %}">Delete</a></span></p>
                        {% endif %}
                    </footer>
                </div>
            </div>

            {% endfor %}

            {% else %}

        {% endif %}
        </div>
    </div>
</div>


    <div class="columns">
    <div class="column is-one-fifth"></div>
        <div class="column">

    {% if latest_news %}

        <div class="container default ce">
            <div class="section heading is-centered">
                <h4 class="title has-text-grey-light  has-text-centered is-bold">News</h4>
            </div>
        </div>

        <div class="box">
            <article class="media">
            <div class="media-left">
              <figure class="image is-align-self-auto">
                <a href="{% url 'all-news' %}"><img src="{% static 'sample_logo.png' %}" alt="Image"></a>
              </figure>
            </div>
            <div class="media-content">
              <div class="content">
                <p>
                  <strong>{{ latest_news.title }}</strong> <small>{{ latest_news.date }}</small> <small>{{ n.time }}</small>
                  <br>
                  {{ latest_news.content }}
                </p>
              </div>

    {% endif %}

            </div>
          </article>
        </div>

        </div>
    <div class="column is-one-fifth"></div>
    </div>

{% if artists %}

        <div class="container default ce">
            <div class="section heading is-centered">
                <h4 class="title has-text-grey-light  has-text-centered is-bold">Talents</h4>
            </div>
        </div>

    <div class="container is-fullheight">
    <div class="table-container is-fullheight">
        <div class="columns mt-3 is-1 is-variable">


            {% for a in artists %}
            <div class="column is-4-tablet is-3-desktop">
                <div class="card help">
                    <div class="card-image has-text-centered px-6">
                        <a href="{% url 'all-artists' %}"><img src="{% static 'sample_picture.jpg' %}" alt=""></a>
                    </div>
                    <div class="card-content">
                        <h3 class="is-size-4 has-text-centered">{{ a.first_name }} {{ a.last_name }}</h3>
                    </div>
                </div>
            </div>

            {% endfor %}

            {% else %}

        {% endif %}
        </div>
    </div>
</div>

{% endblock %}

templates/core/navbar.html
{% load static %}
<nav class="navbar is-fullheight has-shadow" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'home' %}">
          <img src="https://bulma.io/images/bulma-logo.png" alt="Bulma: a modern CSS framework based on Flexbox" width="112" height="28">
        </a>

    <div class="navbar-start">
        <div class="navbar-item is-boxed"><a href="{% url 'all-plays' %}">Watch now</a></div>
        {% if perms.core.add_play %}
        <div class="navbar-item is-boxed"><a href="{% url 'create-play' %}">Create play</a></div>
        {% endif %}
        <div class="navbar-item is-boxed"><a href="{% url 'all-artists' %}">Artists</a></div>
        <div class="navbar-item is-boxed"><a href="{% url 'all-news' %}">News</a></div>
        <div class="navbar-item is-boxed"><a href="{% url 'register_admin' %}">Staff Only</a></div>


        {% if user.is_authenticated %}
            <div class="navbar-item is-boxed"><a href="#">Buy a ticket</a></div>
            <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link" href="{% url 'profile' %}">Profile</a>
                <div class="navbar-dropdown is-boxed">
                  <a class="navbar-item" href="#">My Profile</a>
                  <a class="navbar-item" href="#">Change password</a>
                    <hr class="navbar-divider">
                  <a class="navbar-item" href="{% url 'logout' %}">Logout</a>
                </div>
            </div>

        {% else %}
                <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link" href="#">Profile</a>
                <div class="navbar-dropdown is-boxed">
                  <a class="navbar-item" href="{% url 'login' %}">Sign in</a>
                    <hr class="navbar-divider">
                  <a class="navbar-item" href="{% url 'register' %}">Register</a>
                </div>
            </div>
        {% endif %}




    <div class="navbar-end is-right">
      <div class="navbar-item">
          {% if user.is_authenticated %}
          <div class="navbar-item"> Welcome {{ user }} </div>
          {% endif %}
        <div class="control">

            <form class="is-active" method=POST action="{% url 'search_results' %}">
                {% csrf_token %}
                <input class="input" type="text" placeholder="Search" aria-label="Search" name="searched">
            </form>

        </div>
      </div>
    </div>

    </div>
  </div>
</nav>

templates/core/news_all.html
{% extends 'core/Base.html' %}

{% load static %}
{% block content %}

<div class="container is-fullheight">
    <div class="columns">
        <div class="column is is-one-fifth"></div>
        <div class="column">

        {% if all_news %}
            <div class="block"><strong>All news</strong></div>
        {% else %}
            <div class="block"><strong>No News</strong></div>
        {% endif %}

            {% for n in all_news %}
            <div class="box">


  <article class="media">
    <div class="media-left">
      <figure class="image is-align-self-auto">
        <a href="{% url 'details-news' pk=n.pk %}"><img src="{% static 'sample_logo.png' %}" alt="Image"></a>
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <p>
          <strong>{{ n.title }}</strong> <small>{{ n.date }}</small> <small>{{ n.time }}</small>
          <br>
          {{ n.content }}
        </p>
      </div>
      <nav class="level">
        <div class="level-right">
            {% if perms.core.change_news %}
            <button class="button is-small"><a href="{% url 'edit-news' pk=n.pk %}">Edit</a></button>
            {% endif %}
            {% if perms.core.delete_news %}
            <button class="button is-small"><a href="{% url 'delete-news' pk=n.pk %}">Delete</a></button>
            {% endif %}
        </div>
      </nav>

    </div>
  </article>
</div>

{% endfor %}

{% if is_paginated %}
<ul class="pagination">
    {% if page_obj.has_previous %}
        <li>
            <span><a href="?page={{ page_obj.previous_page_number }}">Previous</a></span>
        </li>
    {% endif %}
        <li class=""><span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span></li>
    {% if page_obj.has_next %}
        <li><span><a href="?page={{ page_obj.next_page_number }}">Next</a></span></li>
    {% endif %}
</ul>
{% endif %}
        {% if perms.core.add_news %}
        <button class="button is-medium"><a href="{% url 'create-news' %}">Create</a></button>
        {% endif %}
        </div>
        <div class="column is is-one-fifth"></div>
        </div>
    </div>

{% endblock %}

templates/core/news_details.html
{% extends 'core/Base.html' %}

{% load static %}
{% block content %}

<div class="container is-fullheight">
    <div class="columns">
        <div class="column is is-one-fifth"></div>
        <div class="column">

        <div class="box">

  <article class="media">
    <div class="media-left">
      <figure class="image is-align-self-auto">
        <a href="{% url 'details-news' pk=news.pk %}"><img src="{% static 'sample_logo.png' %}" alt="Image"></a>
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <p>
          <strong>{{ news.title }}</strong> <small>{{ n.date }}</small> <small>{{ n.time }}</small>
          <br>
          {{ n.content }}
        </p>
      </div>
      <nav class="level">
        <div class="level-right">
            {% if perms.core.change_news %}
            <button class="button is-small"><a href="{% url 'edit-news' pk=news.pk %}">Edit</a></button>
            {% endif %}
            {% if perms.core.delete_news %}
            <button class="button is-small"><a href="{% url 'delete-news' pk=news.pk %}">Delete</a></button>
            {% endif %}
        </div>
      </nav>

    </div>
  </article>
</div>

        </div>
        <div class="column is is-one-fifth"></div>
        </div>
    </div>

{% endblock %}